[package]
name = "rust-concurent-patterns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
futures = "0.3.30"
tokio = { version = "1.38.0", features = ["full"] }
crossbeam-channel = "0.5.13"
